# https://taskfile.dev

version: '3'
tasks:
  pre-reqs:
    - git submodule update --init --recursive
    - sudo apt install hugo git -y
  default:
    cmds:
      - git submodule update --init --recursive
      - git submodule update --recursive --remote
      - hugo server -D --disableFastRender --enableGitInfo
    silent: false
  commit:
    cmds:
    - mdformat content
  remove_hooks:
    - pre-commit uninstall
    - pre-commit clean
    - rm .git/hooks -rf
