# https://taskfile.dev

version: '3'
tasks:
  pre-reqs:
    - sudo apt install hugo git -y
  default:
    deps: [pre-reqs]
    cmds:
      - hugo server -D
    silent: false
  commit:
    cmds:
    - mdformat content
  remove_hooks:
    - pre-commit uninstall
    - pre-commit clean
    - rm .git/hooks -rf
